version: '2.0'
services:
  main-react-app:
    build:
      context: ./main-react-app
    ports:
      - '3000:3000'
    container_name: main-react-app
    stdin_open: true
  micro-react1:
    build:
      context: ./micro-react1
    ports:
      - '3001:80'
    container_name: micro-react1
    stdin_open: true
  micro-react2:
    build:
      context: ./micro-react2
    ports:
      - '3002:80'
    container_name: micro-react2
    stdin_open: true
  nginx:
    container_name: nginx001
    ports:
      - 80:80
    depends_on:
      - main-react-app
      - micro-react1
      - micro-react2
    build:
      context: .
